version: "3"
services:
  project-db:
    image: mariadb:10.1.48-bionic
    container_name: project-dbs
    volumes:
      - "/home/dana-maria/bootcampDev/www/event_management/laravel/docker-containers/db:/var/www/html"
    ports:
      - "3387:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
    networks:
      - project-network
    restart: unless-stopped

  project-webserver:
    image: nginx:alpine
    container_name: project-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "885:80"
      - "8843:443"
    volumes:
      - "/home/dana-maria/bootcampDev/www/event_management/laravel:/var/www/html"
      - "/home/containers/project/docker-compose/nginx/conf.d/:/etc/nginx/conf.d/"
    networks:
      - project-network

  project-app:
    image: amoraresco/it-academy-project:1.2
    container_name: project-apps
    links:
      - project-db
      - project-redis
    ports:
      - "9000:9000"
      - "883:22"
    working_dir: /var/www/html
    volumes:
      - "/home/dana-maria/bootcampDev/www/event_management/laravel:/var/www/html"
    environment:
      - APP_URL=http://myproject.com
      - MAIL_HOST=project-mailhog
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_PORT=1025
      - MAIL_FROM_ADDRESS=danamaria.cozaru@gmail.com
      - MAIL_NAME="PHR API"
      - MAIL_DELAY=2500
      - DB_HOST=project-db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=3306
    networks:
      - project-network
    restart: unless-stopped

  project-mailhog:
    image: mailhog/mailhog
    container_name: project-mailhogs
    ports:
      - "8825:8025"
      - "8125:1025"
    networks:
      - project-network

  project-redis:
    image: redis:3.0
    container_name: project-rediss
    volumes:
      - "/home/containers/project/docker-compose/redis/cache/data:/data"
    ports:
      - "8379:6379"
    restart: unless-stopped
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
